target 'TBOLog_macOS' do
    platform :osx, '10.10'
    use_frameworks!
    pod 'TBOLog', :path => '../', :testspecs => ['Tests']
end

target 'TBOLog_iOS' do
    platform :ios, '9.0'
    use_frameworks!
    pod 'TBOLog', :path => '../', :testspecs => ['Tests']
end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        if target.name.include?'Nimble' or target.name.include?'Quick'
#            target.build_configurations.each do |config|
#                config.build_settings['SWIFT_VERSION'] = '3.2'
#            end
#        end
#    end
#end

